before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
- id: "mink-build"
  binary: mink
  main: ./cmd/mink/main.go
  env:
  - CGO_ENABLED=0
  flags:
    - -mod=vendor
  ldflags:
    # KEEP IN SYNC WITH ./hack/build-flags.sh
    - -X 'github.com/mattmoor/mink/pkg/bundles/kontext.BaseImageString=ghcr.io/mattmoor/github.com/mattmoor/mink/cmd/kontext-expander:v{{.Version}}'
    - -X 'github.com/mattmoor/mink/pkg/builds/buildpacks.PlatformSetupImageString=ghcr.io/mattmoor/github.com/mattmoor/mink/cmd/platform-setup:v{{.Version}}'
    - -X 'github.com/mattmoor/mink/pkg/builds/buildpacks.ExtractDigestImageString=ghcr.io/mattmoor/github.com/mattmoor/mink/cmd/extract-digest:v{{.Version}}'
    - -X 'github.com/mattmoor/mink/pkg/builds/ko.KoImageString=ghcr.io/mattmoor/github.com/google/ko/cmd/ko@:v{{.Version}}'
    - -X 'github.com/mattmoor/mink/pkg/command.BuildDate={{.Date}}'
    - -X 'github.com/mattmoor/mink/pkg/command.Version={{.Version}}'
    - -X 'github.com/mattmoor/mink/pkg/command.CoreReleaseURI=https://github.com/mattmoor/mink/releases/download/v{{.Version}}/core.yaml'
    - -X 'github.com/mattmoor/mink/pkg/command.InMemoryReleaseURI=https://github.com/mattmoor/mink/releases/download/v{{.Version}}/in-memory.yaml'
    - -X 'github.com/mattmoor/mink/pkg/command.GitRevision={{.Commit}}'
  goarch:
    - 386
    - amd64
    - arm64
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
  name_template: "mink_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
  files:
    - LICENSE
  wrap_in_directory: true
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
release:
  draft: false
  prerelease: true
  name_template: "Release {{ .Tag }}"
