# Use :nonroot base image for all containers
defaultBaseImage: gcr.io/distroless/static:nonroot
baseImageOverrides:
  github.com/tektoncd/pipeline/cmd/creds-init: gcr.io/tekton-nightly/github.com/tektoncd/pipeline/build-base:latest
  github.com/tektoncd/pipeline/cmd/git-init: gcr.io/tekton-nightly/github.com/tektoncd/pipeline/build-base:latest
  github.com/tektoncd/pipeline/cmd/entrypoint: mattmoor/busybox  # image must have `cp` in $PATH
