# Use :nonroot base image for all containers
defaultBaseImage: gcr.io/distroless/static:nonroot
baseImageOverrides:
  github.com/tektoncd/pipeline/cmd/git-init: gcr.io/tekton-nightly/github.com/tektoncd/pipeline/git-init-build-base:latest

  # May need root to run files.
  github.com/mattmoor/mink/cmd/kontext-expander: gcr.io/distroless/static:latest

  # Needs go to build stuff!
  github.com/google/ko/cmd/ko: golang:latest
