# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.

required = [
  "knative.dev/test-infra/scripts",
  "knative.dev/test-infra/tools/dep-collector",
  "knative.dev/serving/cmd/activator",
  "knative.dev/serving/cmd/autoscaler",
  "knative.dev/serving/cmd/queue",
  "knative.dev/eventing/cmd/ping/adapter",
  "knative.dev/eventing/cmd/ping/jobrunner",
  "knative.dev/eventing/cmd/broker/ingress",
  "knative.dev/eventing/cmd/broker/filter",
  "knative.dev/eventing/cmd/in_memory/channel_dispatcher",
  "knative.dev/eventing/cmd/in_memory/channel_controller",
  "knative.dev/eventing/cmd/apiserver_receive_adapter",
  "knative.dev/eventing/cmd/pong",
  "knative.dev/eventing-contrib/github/cmd/receive_adapter",
  "knative.dev/eventing-contrib/kafka/source/cmd/receive_adapter",
  "github.com/projectcontour/contour/cmd/contour",
  "contrib.go.opencensus.io/exporter/ocagent",
  "github.com/tektoncd/pipeline/cmd/kubeconfigwriter",
  "github.com/tektoncd/pipeline/cmd/creds-init",
  "github.com/tektoncd/pipeline/cmd/git-init",
  "github.com/tektoncd/pipeline/cmd/entrypoint",
  "github.com/tektoncd/pipeline/cmd/imagedigestexporter",
  "github.com/tektoncd/pipeline/cmd/pullrequest-init",
  "github.com/GoogleCloudPlatform/cloud-builders/gcs-fetcher/cmd/gcs-fetcher",
  "github.com/mattmoor/vmware-sources/cmd/receive_adapter",
]

[[override]]
  name = "knative.dev/pkg"
  branch = "master"

[[override]]
  name = "knative.dev/serving"
  branch = "master"

[[override]]
  name = "knative.dev/eventing"
  branch = "master"

[[override]]
  name = "knative.dev/eventing-contrib"
  branch = "master"

[[override]]
  name = "knative.dev/net-contour"
  branch = "master"

[[override]]
  name = "knative.dev/net-http01"
  branch = "master"

[[override]]
  name = "github.com/tektoncd/pipeline"
  branch = "master"

[[override]]
  name = "github.com/projectcontour/contour"
  branch = "release-1.3"

[[override]]
  name = "k8s.io/klog"
  version = "v0.2.0"

[[override]]
  name = "k8s.io/gengo"
  revision = "e17681d19d3ac4837a019ece36c2a0ec31ffe985"

[[override]]
  name = "github.com/gogo/protobuf"
  version = "v1.3.1"

[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.16.4"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.16.4"

[[override]]
  name = "k8s.io/code-generator"
  version = "kubernetes-1.16.4"

[[override]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.16.4"

[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.16.4"

[[override]]
  name = "k8s.io/apiserver"
  version = "kubernetes-1.16.4"

[[override]]
  name = "k8s.io/metrics"
  version = "kubernetes-1.16.4"

[[override]]
  name = "contrib.go.opencensus.io/exporter/ocagent"
  version = "v0.6.0"

[[override]]
  name = "github.com/coreos/etcd"
  # What's in knative/serving
  revision = "98d308426819d892e149fe45f6fd542464cb1f9d"
  # version = "v3.3.13"

# The dependencies below are required for go-containrregistry.
[[override]]
  name = "github.com/google/go-containerregistry"
  # HEAD as of 2020-03-31
  revision = "3d03ed9b1ca2ad5d78d43832e8e46adc31d2b961"

[[override]]
  name = "github.com/vdemeester/k8s-pkg-credentialprovider"
  version = "v1.17.4"

[[override]]
  name = "k8s.io/legacy-cloud-providers"
  version = "v0.17.3"

[[override]]
  name = "k8s.io/kube-openapi"
  # This is the version at which k8s.io/apiserver depends on this at its 1.16.4 tag.
  revision = "743ec37842bffe49dd4221d9026f30fb1d5adbc4"

[[override]]
  name = "sigs.k8s.io/structured-merge-diff"
  # This is the version at which k8s.io/apiserver depends on this at its 1.16.4 tag.
  version = "1.0.1"

# The dependencies below are required for opencensus.
[[override]]
  name = "google.golang.org/genproto"
  revision = "357c62f0e4bbba7e6cc403ae09edcf3e2b9028fe"

[[override]]
  name = "contrib.go.opencensus.io/exporter/prometheus"
  version = "0.1.0"

[[override]]
  name = "contrib.go.opencensus.io/exporter/zipkin"
  version = "0.1.1"

[[override]]
  name = "github.com/census-instrumentation/opencensus-proto"
  version = "0.2.0"

[[override]]
  name="github.com/golang/protobuf"
  version = "1.3.2"

[prune]
  go-tests = true
  unused-packages = true
  non-go = true

[[prune.project]]
  name = "knative.dev/pkg"
  unused-packages = false
  non-go = false

[[prune.project]]
  name = "knative.dev/serving"
  unused-packages = false
  non-go = false

[[prune.project]]
  name = "github.com/tektoncd/pipeline"
  unused-packages = false
  non-go = false

[[prune.project]]
  name = "knative.dev/eventing"
  unused-packages = false
  non-go = false

[[prune.project]]
  name = "knative.dev/eventing-contrib"
  unused-packages = false
  non-go = false

[[prune.project]]
  name = "knative.dev/net-contour"
  unused-packages = false
  non-go = false

[[prune.project]]
  name = "github.com/projectcontour/contour"
  unused-packages = false
  non-go = false

[[prune.project]]
  name = "github.com/mattmoor/vmware-sources"
  unused-packages = false
  non-go = false

[[prune.project]]
  name = "github.com/mattmoor/bindings"
  unused-packages = false
  non-go = false

[[prune.project]]
  name = "knative.dev/caching"
  unused-packages = false
  non-go = false

[[prune.project]]
  name = "k8s.io/code-generator"
  unused-packages = false
  non-go = false

[[prune.project]]
  name = "knative.dev/test-infra"
  non-go = false
