# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.

required = [
  "knative.dev/test-infra/scripts",
  "knative.dev/test-infra/tools/dep-collector",
  "knative.dev/serving/cmd/activator",
  "knative.dev/serving/cmd/autoscaler",
  "knative.dev/serving/cmd/queue",
  "github.com/projectcontour/contour/cmd/contour",
  "github.com/knative/eventing-contrib/github/cmd/controller",
  "github.com/knative/eventing-contrib/github/cmd/receive_adapter",
]

[[override]]
  name = "github.com/projectcontour/contour"
  branch = "master"

[[override]]
  name = "github.com/mattmoor/net-contour"
  branch = "master"

[[override]]
  name = "k8s.io/klog"
  version = "v0.2.0"

[[override]]
  name = "k8s.io/gengo"
  revision = "e17681d19d3ac4837a019ece36c2a0ec31ffe985"

[[override]]
  name = "istio.io/api"
  version = "1.4.1"

[[override]]
  name = "istio.io/client-go"
  version = "1.4.1"

[[override]]
  name = "github.com/gogo/protobuf"
  version = "v1.3.1"

[[override]]
  name = "k8s.io/kubernetes"
  # From Serving for the LazyAuthConfiguration
  revision = "81753b10df112992bf51bbc2c2f85208aad78335"

[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.15.3"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.15.3"

[[override]]
  name = "k8s.io/code-generator"
  version = "kubernetes-1.15.3"

[[override]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.15.3"

[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.15.3"

[[override]]
  name = "k8s.io/apiserver"
  version = "kubernetes-1.15.3"

[[override]]
  name = "k8s.io/metrics"
  version = "kubernetes-1.15.3"

[[override]]
  name = "github.com/coreos/etcd"
  # What's in knative/serving
  revision = "98d308426819d892e149fe45f6fd542464cb1f9d"
  # version = "v3.3.13"

[[override]]
  name = "github.com/google/go-containerregistry"
  # HEAD as of 2019-09-10
  revision = "b02d448a3705facf11018efff34f1d2830be5724"

[[override]]
  name = "k8s.io/kube-openapi"
  # This is the version at which k8s.io/apiserver depends on this at its 1.15.3 tag.
  revision = "b3a7cee44a305be0a69e1b9ac03018307287e1b0"

[[override]]
  name = "sigs.k8s.io/structured-merge-diff"
  # This is the version at which k8s.io/apiserver depends on this at its 1.15.3 tag.
  revision = "e85c7b244fd2cc57bb829d73a061f93a441e63ce"

[[override]]
  name = "knative.dev/pkg"
  branch = "master"

[[override]]
  name = "knative.dev/eventing-contrib"
  branch = "master"

[[override]]
  name = "go.opencensus.io"
  # Needed because this includes the appropriate version of metricsdata
  version = "v0.22.0"

# The dependencies below are required for opencensus.
[[override]]
  name = "google.golang.org/genproto"
  revision = "357c62f0e4bbba7e6cc403ae09edcf3e2b9028fe"

[[override]]
  name = "contrib.go.opencensus.io/exporter/prometheus"
  version = "0.1.0"

[[override]]
  name = "contrib.go.opencensus.io/exporter/zipkin"
  version = "0.1.1"

[[override]]
  name = "github.com/census-instrumentation/opencensus-proto"
  version = "0.2.0"

[[override]]
  name="github.com/golang/protobuf"
  version = "1.3.2"

[prune]
  go-tests = true
  unused-packages = true
  non-go = true

[[prune.project]]
  name = "knative.dev/pkg"
  unused-packages = false
  non-go = false

[[prune.project]]
  name = "knative.dev/serving"
  unused-packages = false
  non-go = false

[[prune.project]]
  name = "knative.dev/eventing-contrib"
  unused-packages = false
  non-go = false

[[prune.project]]
  name = "github.com/mattmoor/net-contour"
  unused-packages = false
  non-go = false

[[prune.project]]
  name = "knative.dev/caching"
  unused-packages = false
  non-go = false

[[prune.project]]
  name = "k8s.io/code-generator"
  unused-packages = false
  non-go = false

[[prune.project]]
  name = "knative.dev/test-infra"
  non-go = false
