apiVersion: v1
kind: ConfigMap
metadata:
  name: chains-config
  namespace: mink-system
  labels:
    knative.dev/release: devel
# The data can be tweaked at install time, it is commented out
# because these are the default settings.
# data:
#   artifacts.taskrun.format: tekton
#   artifacts.taskrun.storage: tekton
#   artifacts.taskrun.signer: x509
#   artifacts.oci.storage: oci
#   artifacts.oci.format: simplesigning
#   artifacts.oci.signer: x509
