/*
Copyright 2019 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
	v1alpha1 "knative.dev/sample-controller/pkg/apis/samples/v1alpha1"
	scheme "knative.dev/sample-controller/pkg/client/clientset/versioned/scheme"
)

// AddressableServicesGetter has a method to return a AddressableServiceInterface.
// A group's client should implement this interface.
type AddressableServicesGetter interface {
	AddressableServices(namespace string) AddressableServiceInterface
}

// AddressableServiceInterface has methods to work with AddressableService resources.
type AddressableServiceInterface interface {
	Create(*v1alpha1.AddressableService) (*v1alpha1.AddressableService, error)
	Update(*v1alpha1.AddressableService) (*v1alpha1.AddressableService, error)
	UpdateStatus(*v1alpha1.AddressableService) (*v1alpha1.AddressableService, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.AddressableService, error)
	List(opts v1.ListOptions) (*v1alpha1.AddressableServiceList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.AddressableService, err error)
	AddressableServiceExpansion
}

// addressableServices implements AddressableServiceInterface
type addressableServices struct {
	client rest.Interface
	ns     string
}

// newAddressableServices returns a AddressableServices
func newAddressableServices(c *SamplesV1alpha1Client, namespace string) *addressableServices {
	return &addressableServices{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the addressableService, and returns the corresponding addressableService object, and an error if there is any.
func (c *addressableServices) Get(name string, options v1.GetOptions) (result *v1alpha1.AddressableService, err error) {
	result = &v1alpha1.AddressableService{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("addressableservices").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of AddressableServices that match those selectors.
func (c *addressableServices) List(opts v1.ListOptions) (result *v1alpha1.AddressableServiceList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.AddressableServiceList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("addressableservices").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested addressableServices.
func (c *addressableServices) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("addressableservices").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a addressableService and creates it.  Returns the server's representation of the addressableService, and an error, if there is any.
func (c *addressableServices) Create(addressableService *v1alpha1.AddressableService) (result *v1alpha1.AddressableService, err error) {
	result = &v1alpha1.AddressableService{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("addressableservices").
		Body(addressableService).
		Do().
		Into(result)
	return
}

// Update takes the representation of a addressableService and updates it. Returns the server's representation of the addressableService, and an error, if there is any.
func (c *addressableServices) Update(addressableService *v1alpha1.AddressableService) (result *v1alpha1.AddressableService, err error) {
	result = &v1alpha1.AddressableService{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("addressableservices").
		Name(addressableService.Name).
		Body(addressableService).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *addressableServices) UpdateStatus(addressableService *v1alpha1.AddressableService) (result *v1alpha1.AddressableService, err error) {
	result = &v1alpha1.AddressableService{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("addressableservices").
		Name(addressableService.Name).
		SubResource("status").
		Body(addressableService).
		Do().
		Into(result)
	return
}

// Delete takes name of the addressableService and deletes it. Returns an error if one occurs.
func (c *addressableServices) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("addressableservices").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *addressableServices) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("addressableservices").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched addressableService.
func (c *addressableServices) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.AddressableService, err error) {
	result = &v1alpha1.AddressableService{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("addressableservices").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
