apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: hello-bundles
spec:
  description: "Enumerates the uploaded files."
  params:
    - name: dev.mink.sources.bundle
      description: A self-extracting container image.
    - name: the-file
      description: The name of the file to cat

  results:
  - name: message
    description: The final message
    value: $(tasks.greet-it.results.message)

  tasks:
    - name: dump-file
      taskRef:
        name: hello-bundles
      params:
        - name: dev.mink.sources.bundle
          value: $(params["dev.mink.sources.bundle"])
        - name: the-file
          value: "$(params.the-file)"

    - name: greet-it
      runAfter:
      - dump-file
      taskRef:
        name: hello
      params:
        - name: name
          value: "$(tasks.dump-file.results.contents)"
