apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: hello-image
spec:
  description: "Enumerates the uploaded files."
  params:
    - name: dev.mink.images.target
      description: Typically where to publish an image.

  results:
  - name: message
    description: The final message
    value: $(tasks.greet-it.results.message)

  tasks:
    - name: echo-image
      taskRef:
        name: hello-image
      params:
        - name: dev.mink.images.target
          value: $(params["dev.mink.images.target"])

    - name: greet-it
      runAfter:
      - echo-image
      taskRef:
        name: hello
      params:
        - name: name
          value: "$(tasks.echo-image.results.image)"
