apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: hello-image
spec:
  description: "Echo back the image parameter."
  params:
    - name: dev.mink.images.target
      description: Typically where to publish an image.

  results:
    - name: image
      description: The image tag we have been instructed to target.

  steps:
    - name: echo
      image: ubuntu
      command:
        - /bin/bash
      args:
        - -c
        - |
          echo $(params["dev.mink.images.target"]) > /tekton/results/image
