apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: hello-bundles
spec:
  description: "Enumerates the uploaded files."
  params:
    - name: mink-source-bundle
      description: A self-extracting container image.
    - name: the-file
      description: The name of the file to cat

  results:
    - name: contents
      description: The contents of one of an uploaded file.

  steps:
    - name: extract-bundle
      image: $(params.mink-source-bundle)

    - name: echo
      image: ubuntu
      command:
        - /bin/bash
      args:
        - -c
        - |
          cat $(params.the-file) > /tekton/results/contents
