/*
Copyright 2019 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
	v1alpha1 "knative.dev/sample-controller/pkg/apis/samples/v1alpha1"
)

// AddressableServiceLister helps list AddressableServices.
type AddressableServiceLister interface {
	// List lists all AddressableServices in the indexer.
	List(selector labels.Selector) (ret []*v1alpha1.AddressableService, err error)
	// AddressableServices returns an object that can list and get AddressableServices.
	AddressableServices(namespace string) AddressableServiceNamespaceLister
	AddressableServiceListerExpansion
}

// addressableServiceLister implements the AddressableServiceLister interface.
type addressableServiceLister struct {
	indexer cache.Indexer
}

// NewAddressableServiceLister returns a new AddressableServiceLister.
func NewAddressableServiceLister(indexer cache.Indexer) AddressableServiceLister {
	return &addressableServiceLister{indexer: indexer}
}

// List lists all AddressableServices in the indexer.
func (s *addressableServiceLister) List(selector labels.Selector) (ret []*v1alpha1.AddressableService, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.AddressableService))
	})
	return ret, err
}

// AddressableServices returns an object that can list and get AddressableServices.
func (s *addressableServiceLister) AddressableServices(namespace string) AddressableServiceNamespaceLister {
	return addressableServiceNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// AddressableServiceNamespaceLister helps list and get AddressableServices.
type AddressableServiceNamespaceLister interface {
	// List lists all AddressableServices in the indexer for a given namespace.
	List(selector labels.Selector) (ret []*v1alpha1.AddressableService, err error)
	// Get retrieves the AddressableService from the indexer for a given namespace and name.
	Get(name string) (*v1alpha1.AddressableService, error)
	AddressableServiceNamespaceListerExpansion
}

// addressableServiceNamespaceLister implements the AddressableServiceNamespaceLister
// interface.
type addressableServiceNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all AddressableServices in the indexer for a given namespace.
func (s addressableServiceNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.AddressableService, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.AddressableService))
	})
	return ret, err
}

// Get retrieves the AddressableService from the indexer for a given namespace and name.
func (s addressableServiceNamespaceLister) Get(name string) (*v1alpha1.AddressableService, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("addressableservice"), name)
	}
	return obj.(*v1alpha1.AddressableService), nil
}
