name: Periodic Base Images

on:
  schedule:
    - cron: '0 0 * * *'

  workflow_dispatch: {}

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        working-directory: ./
        run: |
          echo '::group:: install crane'
          go get github.com/google/go-containerregistry/cmd/crane@master
          echo '::endgroup::'

      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: tektoncd/pipeline

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      - name: Docker login
        run: |
          docker login ghcr.io -u mattmoor -p ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Build base
        run: |
          # Could be: ${{ steps.buildx.outputs.platforms }}
          docker buildx build \
            --platform linux/amd64,linux/arm64,linux/ppc64le,linux/s390x \
            --file ./images/Dockerfile --tag ghcr.io/mattmoor/tekton-base:latest --push .

      - name: Estargz Optimize images
        run: |
          # Optimize the tekton base in-place
          crane optimize ghcr.io/mattmoor/tekton-base:latest ghcr.io/mattmoor/tekton-base:latest

          # TODO(mattmoor): Profile these for real
          crane optimize gcr.io/distroless/static:nonroot ghcr.io/mattmoor/distroless/static:nonroot \
                --prioritize=/etc/passwd
          crane optimize gcr.io/distroless/static:latest ghcr.io/mattmoor/distroless/static:latest \
                --prioritize=/etc/passwd

          # TODO(mattmoor): Include the shell symlink?
          crane optimize gcr.io/distroless/base:debug ghcr.io/mattmoor/distroless/base:debug \
                --prioritize=/etc/passwd --prioritize=/busybox

          # TODO(mattmoor): What other envoy files are important?
          crane optimize docker.io/envoyproxy/envoy:v1.16.2 ghcr.io/mattmoor/envoy:v1.16.2 \
                 --prioritize=/usr/local/bin/envoy

          crane optimize gcr.io/kaniko-project/executor:latest ghcr.io/mattmoor/kaniko:latest \
                 --prioritize=/kaniko/executor

      - name: Post failure notice to Slack
        uses: rtCamp/action-slack-notify@v2.1.0
        if: ${{ failure() }}
        env:
          SLACK_ICON: http://github.com/knative-automation.png?size=48
          SLACK_USERNAME: sockpuppet
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

          SLACK_CHANNEL: 'mink'
          SLACK_COLOR: '#8E1600'
          MSG_MINIMAL: 'true'
          SLACK_TITLE: Daily Tekton base buildx failed.
          SLACK_MESSAGE: |
            For detailed logs: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
